name: Deploy to Staging

on:
  push:
    branches:
      - "main"

jobs:
  uses: ubuntu-latest
  redploy_everything:
    name: Deploying everything to the staging environment
    steps:
      - name: SSH Into server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          cd CICD/project/

      - name: Pull the latest changes
        run: git pull

      - name: Restart the services
        run: |
          pnpm install
          pnpm run build
          pm2 restart fe-server 
          pm2 restart ws-server
          pm2 restart http-server
