apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-multicontainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multicontainerapp
  template:
    metadata:
      labels:
        app: multicontainerapp
    spec:
      containers:
        - name: nodedb-app
          image: bansalharsh2504/multicontainer-app:03
        - name: mongodb
          image: mongo:latest

---
apiVersion: v1
kind: Service
metadata:
  name: service-multicontainer
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    app: multicontainer
  type: LoadBalancer
