apiVersion: v1
kind: Service
metadata:
  name: service-multicontainerapp
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    app: multicontainerapp
  type: LoadBalancer